// Run the exact pinned Explorer acceptance functions against generated bytes.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { normaliseEndpointLabelIndex } from '../profiles/explorer-runtime/endpointLabels.ts';
import { parseExploratoryPublication } from '../profiles/explorer-runtime/exploratoryPublication.ts';

const read = (path) => readFileSync(new URL('../' + path, import.meta.url));
const json = (path) => JSON.parse(read(path));
const lock = json('profiles/explorer-runtime/vendor-lock.json');
for (const row of lock.files) {
  assert.equal(createHash('sha256').update(read(row.local_path)).digest('hex'), row.sha256, row.local_path);
}
const descriptor = json('full-dmg/okf-explorer.json');
assert.equal(descriptor.consumer.commit, lock.commit);
const publication = parseExploratoryPublication(descriptor);
assert.equal(publication.state, 'valid', publication.warning);
const labels = JSON.parse(gunzipSync(read('full-dmg/data/endpoint-labels.json.gz')));
const registry = normaliseEndpointLabelIndex(labels, descriptor.snapshot);
assert.equal(registry.byRoute.size, descriptor.counts.records + descriptor.counts.resources + descriptor.counts.publishers);
for (const publisher of json('full-dmg/data/publishers.json')) {
  assert.equal(registry.byRoute.get('publisher/' + publisher.name)?.label, publisher.title);
}
for (const part of json('full-dmg/data/manifest.json').chunks.resources) {
  for (const resource of JSON.parse(gunzipSync(read('full-dmg/' + part)))) {
    assert.ok(registry.byRoute.get('resource/' + resource.id)?.label);
    assert.equal(resource.host, new URL(resource.url).hostname);
  }
}
// These are actual browser failures retained as consumer-level controls.
const badDescriptor = structuredClone(descriptor);
badDescriptor.exploratory_publication.banner.message = 'A different warning';
assert.equal(parseExploratoryPublication(badDescriptor).state, 'invalid');
const badLabels = structuredClone(labels);
badLabels.entries[0].label += ' ';
assert.throws(() => normaliseEndpointLabelIndex(badLabels, descriptor.snapshot), /malformed/);
console.log(JSON.stringify({status: 'passed', snapshot: descriptor.snapshot, consumer_commit: lock.commit,
  exploratory_notice: publication.state, endpoint_labels: registry.byRoute.size, regression_controls: 2}));
