"""Additive Reader for source-led manual units and distinct discovery metadata.

Return generated bytes only. Existing logical/combined Reader releases are not
rewritten. Discovery cards decorate their bound evidence units; they never
become extra evidence records, domain concepts or applicability assertions.
"""
from collections import defaultdict
from copy import deepcopy
import gzip
import json

from build_bundle import BASE, PROFILE, REPO, canonical, context, digest, source_text_block, yaml_bytes
from build_context_corpus import deterministic_gzip
from build_context_discovery import require
from build_full_dmg import CHUNK, bucket, build_search, utc_key, role, role_label, source_dates
from build_combined_reader import add_semantics, endpoint_labels, emit_semantics, source_record

OUTPUT = "structured-context"
TITLE = "DWP guidance: source-led manual structure"
FACETS = {
    "source_heading": "Source headings",
    "concept": "Authored concept references",
    "source_family": "Source family",
    "source_role": "Source document role",
    "source_kind": "Source document kind",
    "boundary_status": "Boundary status",
    "unit_kind": "Unit kind",
}
NO_HEADING = "No source heading recorded"
READER_POSTINGS_COMPLETENESS_THRESHOLD = 50_000
READER_ENDPOINT_LABEL_LIMIT = 100_000
READER_ENDPOINT_TEXT_LIMIT = 48 * 1024 * 1024


def declare_postings_completeness(search, put):
    """Preserve the whole index under the consumer's conservative threshold.

    Explorer's max_postings_per_token marks common-term completeness; it does
    not reject larger bound arrays. True lexicon frequencies and every posting
    remain intact. Such queries receive the consumer's existing uncertainty.
    """
    actual = max((len(rows) for rows in search["postings"].values()), default=0)
    overflow = [{"token": token, "document_frequency": len(rows)}
                for token, rows in sorted(search["postings"].items())
                if len(rows) > READER_POSTINGS_COMPLETENESS_THRESHOLD]
    counts = search["manifest"]["counts"]
    counts.update(max_postings_per_token=max(1, min(actual, READER_POSTINGS_COMPLETENESS_THRESHOLD)),
                  actual_max_postings_per_token=actual,
                  tokens_above_postings_completeness_threshold=len(overflow))
    report = {"schema": "okf-reader-postings-completeness.v1",
              "consumer_completeness_threshold": READER_POSTINGS_COMPLETENESS_THRESHOLD,
              "actual_max_postings_per_token": actual,
              "stored_postings": sum(len(rows) for rows in search["postings"].values()),
              "dropped_postings": 0, "tokens_above_threshold": overflow,
              "meaning": "All records, postings and true lexicon frequencies are retained. Explorer conservatively marks queries using an above-threshold term as capped-postings with uncertain totals. This is a Reader search boundary, not evidence deletion or an Ask OKF completeness claim."}
    path = "data/search/postings-completeness.json"
    put(path, report)
    search["manifest"]["postings_completeness"] = path
    return report


def validate_endpoint_label_budget(labels):
    """Match the existing Reader catalogue ceilings before emitting a release."""
    require(len(labels) <= READER_ENDPOINT_LABEL_LIMIT, "Reader endpoint label catalogue exceeds supported entry limit")
    # JavaScript measures UTF-16 code units, including two units for astral text.
    fields = (value for row in labels for value in
              [row["route"], row["iri"], row["label"], row["language"], row["type"],
               row["label_authority"]["class"], row["label_authority"]["source"]])
    text_units = sum(len(value.encode("utf-16-le")) // 2 for value in fields)
    require(text_units <= READER_ENDPOINT_TEXT_LIMIT, "Reader endpoint label catalogue exceeds supported text limit")
    return {"entries": len(labels), "retained_text_units": text_units,
            "entry_limit": READER_ENDPOINT_LABEL_LIMIT, "retained_text_limit": READER_ENDPOINT_TEXT_LIMIT}


def build_reader_search(records, full_text, snapshot, put):
    """Index aliases as navigation metadata without creating tag endpoints.

    The wire format's mask 32 denotes navigation metadata. Alias-only matches
    remain separate from source-text mask 8; result tags retain actual tags.
    """
    searchable = [{**row, "tags": list(dict.fromkeys([*row["tags"], *row.get("discovery_aliases", [])]))}
                  for row in records]
    search = build_search(searchable, full_text, snapshot, put)
    for result in search["results"]:
        row = records[result["ordinal"]]
        result["tags"] = list(row["tags"])
        result["discovery_aliases"] = list(row.get("discovery_aliases", []))
    search["manifest"]["navigation_metadata"] = {
        "field_mask": 32, "fields": ["tags", "discovery_aliases"],
        "meaning": "Tags and source-bound discovery aliases are indexed as navigation metadata, separately from source text. Aliases remain metadata, not conceptual tags or evidence."}
    return search


def bound_cards(units, card_metadata):
    """Check complete-record bindings without promoting cards to evidence."""
    if card_metadata is None:
        return {}
    require(isinstance(card_metadata, list), "Reader discovery cards must be a list")
    cards = {card["evidence_id"]: card for card in card_metadata}
    require(len(cards) == len(card_metadata), "Duplicate Reader discovery evidence identity")
    require(len({card["id"] for card in card_metadata}) == len(cards), "Duplicate Reader discovery card identity")
    require(set(cards) == {unit["id"] for unit in units}, "Reader discovery/evidence census differs")
    for unit in units:
        card = cards[unit["id"]]
        # Context commitments use canonical JSON without the file terminator.
        require(card["id"] != unit["id"] and card["evidence_sha256"] == digest(canonical(unit)[:-1]),
                "Reader discovery card has a stale complete-record binding")
        require(card["access"] == unit["access"], "Reader discovery access differs from evidence")
        require(card["assertion_status"] in {"normalized", "inferred", "model-derived"}
                and card["authority"]["class"] in {"derived", "model-assisted", "synthetic"},
                "Reader discovery metadata must not claim official authority")
    return cards


def emit_reader(inputs, corpus, units, semantic, declarations, corpus_outputs, card_metadata=None):
    outputs, metadata = {}, {}
    snapshot = corpus["bundle"]["snapshot"]
    when = max((p["captured_at"] for r in [*semantic["records"], *units] for p in r["provenance"]), key=utc_key)
    records, resources, edges, full_text = [], [], [], {}
    all_context = {**semantic, "records": [*semantic["records"], *units]}
    add_semantics(records, resources, edges, full_text, {**all_context, "assertions": []}, when)
    # V3 intentionally keeps assertions out of its bounded semantic base. Bind
    # projection provenance to actual retained assertion shards, not imaginary
    # assertions[n] fields in base-index.json. Chunk-local indices are exact.
    for offset in range(0, len(semantic["assertions"]), CHUNK):
        shard = {"schema": "okf-reader-context-assertions.v1", "snapshot": snapshot,
                 "assertions": semantic["assertions"][offset:offset + CHUNK]}
        path = f"data/context-assertions/{offset // CHUNK:04d}.json"
        raw = canonical(shard)
        require(len(raw) <= 64 * 1024 * 1024, "Reader assertion provenance shard exceeds byte limit")
        outputs[path] = raw
        add_semantics(records, resources, edges, full_text, {"records": [], "assertions": shard["assertions"]},
                      when, OUTPUT + "/" + path, digest(raw))
    # The shared projection also handles authored assertions. This corpus adds
    # normalised literal source references, so its derivation wording must not
    # describe every edge as authored or imply a newly verified quotation.
    for edge in edges:
        edge["derivation"] = BASE + "rules/structured-context-assertion-projection-v1"
        for evidence in edge["evidence"]:
            evidence["rationale"] = "Preserved captured provenance from a source-bound context assertion; this projection does not invent a source quotation."
    cards = bound_cards(units, card_metadata)
    concepts = {r["id"]: r for r in semantic["records"] if r["kind"] == "concept"}
    references = defaultdict(set)
    for edge in semantic["assertions"]:
        if edge["source"] in concepts:
            references[edge["target"]].add(concepts[edge["source"]]["label"])
    unit_map = {r["id"]: r for r in units}
    source_documents = {}
    extensions = corpus.get("extensions", {})
    source_groups = extensions.get("source_groups", corpus.get("source_groups", []))
    require(source_groups, "Reader source inventory bindings are missing")
    for group in source_groups:
        inventory = json.loads(inputs.read(group["inventory"]["repository_path"], group["inventory"]["sha256"]))
        source_documents.update({(group["id"], d["id"]): d for d in inventory["documents"]})
    # One PDF resource per source document; each unit already exposes its exact
    # page spans. Repeating the same PDF resource for every paragraph inflates
    # the endpoint catalogue and obscures the document/unit distinction.
    document_resources, document_records = {}, []
    for document_key, doc in sorted(source_documents.items()):
        family, document_id = document_key
        route = "document/structured/" + family + "/" + document_id + "/pdf-" + doc["sha256"][:16]
        document, resource = source_record(route, doc["title"],
            "# " + doc["title"] + "\n\nSource document for the source-led units. Exact page locations are retained in each unit’s source spans. Documents with no extracted text remain listed. No complete policy or current applicability is asserted.", doc, family=family.upper())
        document.update(boundary_status="Not applicable", unit_kind="Source document", concept=["No authored reference"],
                        source_heading=[NO_HEADING], source_kind=doc.get("kind") or "Not recorded")
        document_records.append(document); resources.append(resource)
        full_text[route] = document["narrative"]["body"]
        document_resources[document_key] = resource["id"]
    for row in records:
        row.update(boundary_status="Not applicable", unit_kind="Not applicable", source_heading=[NO_HEADING], source_kind="Not applicable",
                   concept=sorted(references[row["id"]]) or ["No authored reference"])
        item = unit_map.get(row["id"])
        if not item:
            continue
        unit = item["evidence_unit"]
        source = item["provenance"][0]
        family = row["route"].split("/")[1].upper()
        document_id = row["route"].split("/")[2]
        document_key = (family.lower(), document_id)
        doc = source_documents[document_key]
        card = cards.get(item["id"])
        headings = list(dict.fromkeys(card["heading_path"])) if card else []
        captured_role = role_label(role(doc))
        resource_id = document_resources[document_key]
        row.update(type="Logical evidence unit", record_type="Logical evidence unit",
            publisher="dwp", publisher_title="DWP source; independent extraction",
            source_family=family, source_role=captured_role,
            source_adapter="structured-source-spans-v1", source_tier="official-source-unreviewed-extraction",
            boundary_status=unit["boundary_status"], unit_kind=unit["kind"],
            source_heading=headings or [NO_HEADING], source_kind=doc.get("kind") or "Not recorded",
            document_id=document_id, volume="See source document",
            formats=["PDF"], tags=list(dict.fromkeys([family, unit["kind"], unit["boundary_status"], captured_role,
                                                     *headings])),
            discovery_aliases=list(card["search_aliases"]) if card else [],
            resource_ids=[resource_id], resource_count=1, url=source["url"],
            license_id="uk-ogl", license_title="Open Government Licence v3.0", license_source_id=item["rights"])
        # This is source text with an authored/machine boundary, not authored prose.
        row["provenance"].update(authority=item["authority"], source_sha256=source["source_sha256"],
            literal_sha256=digest(item["text"].encode()), evidence_unit=unit,
            date_roles=source_dates(doc))
        row["extras"] = {"evidence_unit": unit, "source_dates": row["provenance"]["date_roles"]}
        if card:
            row["extras"]["discovery_card"] = deepcopy(card)
        discovery_body = ("\n\n## Discovery metadata — not evidence\n\n"
            + "The source headings and extractive preview help find this unit. They do not establish legal applicability or replace the complete source text below. "
            + "Status: " + card["assertion_status"] + "; authority: " + card["authority"]["class"] + ".\n\n"
            + source_text_block("Heading path: " + " > ".join(headings) + "\n\n" + card["summary"])
            + "\n\n" + card["scope"] + "\n\nComplete evidence-record SHA-256: `" + card["evidence_sha256"] + "`."
            if card else "")
        row["narrative"]["body"] = ("# " + item["label"] + "\n\n**Source extraction; " + unit["boundary_status"]
            + "; " + unit["completeness"] + ". Specialist review required.**\n\n" + item["scope"]
            + discovery_body
            + "\n\n## Captured source text\n\n" + source_text_block(item["text"])
            + "\n\n## Source spans\n\nOffsets are half-open UTF-8 byte offsets in extracted text.\n\n"
            + "\n".join(f"- [{s['locator']}]({s['source_url']}): source bytes {s['source_start']}–{s['source_end']}; fragment SHA-256 `{s['literal_sha256']}`."
                for s in unit["spans"]))
    records.extend(document_records)
    records.sort(key=lambda r: r["route"])
    edges.sort(key=lambda r: r["id"])
    require(len({r["id"] for r in records}) == len(records), "Duplicate structured Reader identity")
    known = {r["route"] for r in records}
    require(all(e["source"] in known and e["target"] in known for e in edges), "Unresolved Reader edge")

    def put(path, value):
        raw = canonical(value)
        require(len(raw) <= 64 * 1024 * 1024, "Reader decoded byte limit")
        outputs[path] = deterministic_gzip(raw) if path.endswith(".gz") else raw
        metadata[path] = {"path": path, "bytes": len(outputs[path]), "sha256": digest(outputs[path]),
            "decoded_bytes": len(raw), "decoded_sha256": digest(raw), "snapshot": snapshot}
        return metadata[path]

    def bind(path):
        return {"path": path, "bytes": len(outputs[path]), "sha256": digest(outputs[path])}

    shard_groups = {}
    for kind, rows in (("datasets", records), ("resources", resources), ("relationships", edges)):
        shard_groups[kind] = [put(f"data/{kind}-{i // CHUNK:04d}.json.gz", rows[i:i + CHUNK]) for i in range(0, len(rows), CHUNK)]
    locations, adjacent = defaultdict(dict), defaultdict(dict)
    for n, row in enumerate(records):
        locations[bucket(row["route"])][row["route"]] = [n // CHUNK, n % CHUNK]
    for edge in edges:
        for route in {edge["source"], edge["target"]}:
            adjacent[bucket(route)].setdefault(route, []).append(edge)
    locator = {}
    for key, rows in sorted(locations.items()):
        path = f"data/locator/{key}.json"
        put(path, rows); locator[key] = bind(path)
    put("data/locator/manifest.json", {"schema": "okf-record-locator-sharded.v1", "algorithm": "fnv1a32-prefix-2", "snapshot": snapshot,
        "records": len(records), "chunk_size": CHUNK, "record_chunks": [r["path"] for r in shard_groups["datasets"]], "buckets": locator, "bucket_count": len(locator)})
    adjacency_shards = [put(f"data/adjacency/{key}.json.gz", rows) for key, rows in sorted(adjacent.items())]
    put("data/adjacency/manifest.json", {"schema": "okf-relationship-adjacency.v1", "algorithm": "fnv1a32-prefix-2", "snapshot": snapshot,
        "routes": sum(map(len, adjacent.values())), "relationships": len(edges), "buckets": {k: f"data/adjacency/{k}.json.gz" for k in sorted(adjacent)}, "shards": adjacency_shards})
    search = build_reader_search(records, full_text, snapshot, put)
    declare_postings_completeness(search, put)
    facets = search["facets"]
    for key in FACETS:
        values = defaultdict(list)
        for n, row in enumerate(records):
            for value in row[key] if isinstance(row[key], list) else [row[key]]:
                values[value].append(n)
        path = f"data/search/filters/{key}.json.gz"
        put(path, {"schema": "okf-filter-postings.v1", "key": key, "values": dict(sorted(values.items()))})
        search["manifest"]["entrypoints"]["filter_postings"][key] = path
        facets[key] = [{"value": v, "count": len(ids)} for v, ids in sorted(values.items(), key=lambda p: (-len(p[1]), p[0]))]
    for path in search["manifest"]["entrypoints"]["result_docs"]:
        rows = json.loads(gzip.decompress(outputs[path]))
        for row in rows:
            row.update({key: records[row["ordinal"]][key] for key in FACETS})
            row["tags"] = records[row["ordinal"]]["tags"]
            row["discovery_aliases"] = records[row["ordinal"]].get("discovery_aliases", [])
        put(path, rows)
    put("data/facets.json", facets)
    search_shards = {"search": [{**bind(p), "snapshot": snapshot} for p in sorted(outputs) if p.startswith("data/search/") or p == "data/facets.json"]}
    put("data/search/shards.json", {"snapshot": snapshot, "shards": search_shards})
    search["manifest"].update(shard_metadata="data/search/shards.json", shard_manifest_sha256=digest(canonical(search_shards)))
    put("data/search/manifest.json", search["manifest"])
    counts = {"records": len(records), "datasets": len(records), "resources": len(resources), "relationships": len(edges),
        "publishers": 2, "source_documents": corpus["counts"]["documents"], "source_pages": corpus["counts"]["pages"]}
    publishers = [{"id": "publisher/" + key, "name": key, "title": title,
        "dataset_count": sum(r["publisher"] == key for r in records), "resource_count": len({resource for r in records if r["publisher"] == key for resource in r["resource_ids"]})}
        for key, title in (("dwp", "DWP source; independent extraction"), ("independent-project", "Independent project-authored research"))]
    put("data/publishers.json", publishers)
    put("data/overview.json", {"schema": "okf-large-overview.v1", "title": TITLE, "generated_at": when, "counts": counts,
        "recent_datasets": search["results"][:12], "notices": corpus["limitations"], "facet_previews": {k: v[:15] for k, v in facets.items()}})
    labels = endpoint_labels(records, resources, publishers, facets)
    put("data/endpoint-label-budget.json", {"schema": "okf-reader-endpoint-label-budget.v1",
        "snapshot": snapshot, **validate_endpoint_label_budget(labels),
        "policy": "No endpoint rows are truncated. Discovery aliases remain separately labelled and searchable metadata; they do not create conceptual tag endpoints."})
    put("data/endpoint-labels.json.gz", {"schema": "okf-explorer-endpoint-label-index.v1", "snapshot": snapshot, "generated_at": when,
        "default_language": "en-GB", "opaque_identifier_patterns": [], "entries": labels, "counts": {"entries": len(labels)}})
    put("data/analysis.json", {"schema": "okf-analysis.v1", "snapshot": snapshot, "facet_analysis": []})
    put("data/manifest.json", {"title": TITLE, "snapshot": snapshot, "generated_at": when, "counts": counts,
        "chunks": {**{k: [r["path"] for r in v] for k, v in shard_groups.items()}, "publishers": [bind("data/publishers.json")]}, "shards": shard_groups,
        "indexes": {"overview": "data/overview.json", "facets": "data/facets.json", "search": "data/search/manifest.json", "analysis": "data/analysis.json",
            "record_locator": bind("data/locator/manifest.json"), "relationship_adjacency": "data/adjacency/manifest.json", "endpoint_labels": bind("data/endpoint-labels.json.gz")}})
    semantic_manifest = emit_semantics(records, edges, all_context, declarations, snapshot, when, put, outputs, bind)
    semantic_manifest["canonical_authoring"] = "Frozen source-unit identities, source-led structure and references, retained neutral concepts, and explicit domain-profile/logical-units proposals. Discovery cards are separate navigation metadata. Boundaries and relationships remain distinct and require specialist review."
    semantic_manifest["projection_scope"] = "Identity and definition nodes, direct triples and the same reified assertions. Exact unit text and byte-span provenance remain in the bound Reader and context records."
    put("data/semantic/manifest.json", semantic_manifest)
    # Keep the existing large-corpus wire format, replacing every data binding.
    descriptor = deepcopy(json.loads(inputs.read("combined/okf-explorer.json")))
    # Teaching routes belong to the combined corpus, not this separate unit corpus.
    descriptor.pop("learning_presentation", None)
    descriptor.update(title=TITLE, description=corpus["limitations"][0], snapshot=snapshot, snapshot_id=snapshot, counts=counts, generated_at=when)
    descriptor.pop("consumer", None)  # Exact tested engine identity is bound by the evaluation receipt.
    descriptor["entrypoints"] = {"markdown_index": "index.md"}
    descriptor["entrypoint_integrity"] = {}
    for key, path in {"data_manifest": "data/manifest.json", "overview_index": "data/overview.json", "search_manifest": "data/search/manifest.json",
        "record_locator": "data/locator/manifest.json", "relationship_adjacency": "data/adjacency/manifest.json", "endpoint_labels": "data/endpoint-labels.json.gz"}.items():
        descriptor["entrypoints"][key] = bind(path) if key in {"record_locator", "endpoint_labels"} else path
        descriptor["entrypoint_integrity"][key] = bind(path)
    for key, path in (("context_assembly", "base-index.json"), ("context_corpus", "manifest.json")):
        ref = {"path": path, "bytes": len(corpus_outputs[path]), "sha256": digest(corpus_outputs[path])}
        descriptor["entrypoints"][key] = ref; descriptor["entrypoint_integrity"][key] = ref
    descriptor["extensions"] = {"okf-explorer-presentation.v1": {"schema": "okf-explorer-presentation.v1", "snapshot": snapshot,
        "status": "experimental", "defaults": {"facet_mode": "suggested"}, "facets": [{"key": k, "label": label,
        "description": "Discovery and review status only; not an applicability claim.", "order": n, "default_state": "pinned", "open_control": "list", "value_order": "count-desc"}
        for n, (k, label) in enumerate(FACETS.items())]}}
    source_identity = {"unit_manifest": extensions.get("unit_manifest", corpus.get("unit_producer")), "source_groups": source_groups}
    require(source_identity["unit_manifest"], "Reader source-unit producer binding is missing")
    put("data/source-identity.json", source_identity)
    descriptor["plane_roots"] = {"source": digest(canonical(source_identity)), "semantic": semantic_manifest["semantic_identity"]["sha256"],
        "data": digest(canonical(shard_groups["datasets"])), "search": digest(canonical(search_shards)), "presentation": digest(canonical(descriptor["extensions"]))}
    descriptor["exploratory_publication"].update(snapshot_id=snapshot, generated_at=when, applicable_plane_roots=descriptor["plane_roots"],
        limitations=corpus["limitations"], permitted_claims=["Exact source-byte accounting, source-led candidate units, separate discovery metadata and explicit relationship provenance; no complete legal answerability."])
    descriptor["source"] = {"url": REPO, "identity": bind("data/source-identity.json"), "scope": corpus["scope"]}
    descriptor["vocabulary"]["search_placeholder"] = "Search source units and headings"
    put("okf-explorer.json", descriptor)
    control = {"@context": context(), "@id": BASE + "id/bundle/" + OUTPUT, "@type": "okf:Bundle", "title": TITLE,
        "description": corpus["limitations"][0], "version": "0.1.0", "status": "experimental", "descriptor": {"@id": BASE + OUTPUT + "/okf-explorer.json"},
        "semanticDescriptor": {"@id": BASE + OUTPUT + "/okf-bundle.yamlld"}, "home": {"@id": REPO}, "profile": {"@id": PROFILE},
        "publisher": {"@id": "https://github.com/chris-page-gov"}, "license": {"@id": REPO + "/blob/main/NOTICE.md"},
        "snapshot_id": snapshot, "semantic_manifest": bind("data/semantic/manifest.json"), "counts": semantic_manifest["counts"],
        "assertion_scope": "real-world", "exploratory_publication": descriptor["exploratory_publication"]}
    outputs["okf-bundle.yamlld"] = yaml_bytes(control)
    put("okf-bundle.jsonld", control)
    outputs["index.md"] = ("# " + TITLE + "\n\n" + "\n\n".join(corpus["limitations"])
        + "\n\nSource headings and document roles are navigation metadata; only explicitly authored domain concepts appear in the concept facet. Discovery cards are previews of bound complete evidence units, not extra evidence. Reader search indexes source text, labels, navigation tags and separately retained source-bound discovery aliases; Ask OKF applies its separately versioned two-channel ranking.\n"
        + "\n[Reader descriptor](okf-explorer.json) · [Ask corpus](manifest.json) · [Logical-unit boundaries](../docs/logical-evidence-units.md).\n").encode()
    return outputs
